# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '声网视频推流' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 声网视频推流

  target '声网视频推流Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '声网视频推流UITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry' 
pod 'AgoraRtcEngine_iOS', '~> 2.1.3'

end
